### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by blackz13** [opentibia/yatc#1]
i'm having this problems and i don't know how to fix, and i don't know where add th folder "bin" too.

1>------ Build started: Project: yatc, Configuration: Release Win32 ------
1>  creatureui.cpp
1>c:\users\kessya\downloads\yatc-master\sprite.h(54): warning C4244: 'return' : conversion from 'int' to 'float', possible loss of data
1>c:\users\kessya\downloads\yatc-master\sprite.h(55): warning C4244: 'return' : conversion from 'int' to 'float', possible loss of data
1>c:\users\kessya\downloads\yatc-master\sprite.h(56): warning C4244: 'return' : conversion from 'int' to 'float', possible loss of data
1>c:\users\kessya\downloads\yatc-master\sprite.h(57): warning C4244: 'return' : conversion from 'int' to 'float', possible loss of data
1>c:\users\kessya\downloads\yatc-master\font.h(33): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>c:\users\kessya\downloads\yatc-master\font.h(33): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>c:\users\kessya\downloads\yatc-master\font.h(33): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>c:\users\kessya\downloads\yatc-master\font.h(33): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>c:\users\kessya\downloads\yatc-master\font.h(33): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>c:\users\kessya\downloads\yatc-master\font.h(33): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>c:\users\kessya\downloads\yatc-master\gamecontent/creature.h(126): warning C4250: 'Creature' : inherits 'CreatureUI::CreatureUI::Blit' via dominance
1>          c:\users\kessya\downloads\yatc-master\gamecontent\../creatureui.h(33) : see declaration of 'CreatureUI::Blit'
1>c:\users\kessya\downloads\yatc-master\net/connection.h(37): warning C4005: 'EWOULDBLOCK' : macro redefinition
1>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\errno.h(132) : see previous definition of 'EWOULDBLOCK'
1>..\creatureui.cpp(68): warning C4244: '=' : conversion from 'float' to 'int', possible loss of data
1>..\creatureui.cpp(69): warning C4244: '=' : conversion from 'float' to 'int', possible loss of data
1>..\creatureui.cpp(147): warning C4244: 'argument' : conversion from 'uint32_t' to 'float', possible loss of data
1>..\creatureui.cpp(159): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(159): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(165): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(165): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(168): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(168): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(217): warning C4244: '=' : conversion from 'float' to 'int', possible loss of data
1>..\creatureui.cpp(218): warning C4244: '=' : conversion from 'float' to 'int', possible loss of data
1>..\creatureui.cpp(242): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(242): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(243): warning C4244: 'argument' : conversion from 'double' to 'float', possible loss of data
1>..\creatureui.cpp(243): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(243): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(266): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(266): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(269): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(269): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(272): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(272): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(275): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(275): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(279): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(279): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(282): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(282): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(286): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(286): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(289): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(289): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(293): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(293): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(296): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(296): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(308): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(308): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(311): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(311): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(314): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(314): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(317): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(317): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(320): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(320): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(332): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(332): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(335): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(335): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(338): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(338): warning C4244: 'argument' : conversion from 'int' to 'float', possible loss of data
1>..\creatureui.cpp(412): warning C4244: '+=' : conversion from 'double' to 'float', possible loss of data
1>C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xmemory(208): error C2440: 'initializing' : cannot convert from 'int' to 'Sprite *'
1>          Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
1>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\xmemory(280) : see reference to function template instantiation 'void std::allocator<_Ty>::construct<int>(Sprite **,_Other &&)' being compiled
1>          with
1>          [
1>              _Ty=Sprite *,
1>              _Other=int
1>          ]
1>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\vector(668) : see reference to function template instantiation 'void std::_Cons_val<std::allocator<_Ty>,Sprite*,int>(_Alloc &,_Ty1 *,_Ty2 &&)' being compiled
1>          with
1>          [
1>              _Ty=Sprite *,
1>              _Alloc=std::allocator<Sprite *>,
1>              _Ty1=Sprite *,
1>              _Ty2=int
1>          ]
1>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\vector(688) : see reference to function template instantiation 'void std::vector<_Ty>::emplace_back<int>(_Valty &&)' being compiled
1>          with
1>          [
1>              _Ty=Sprite *,
1>              _Valty=int
1>          ]
1>          C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include\vector(675) : see reference to function template instantiation 'std::_Vector_iterator<_Myvec> std::vector<_Ty>::emplace<int>(std::_Vector_const_iterator<_Myvec>,_Valty &&)' being compiled
1>          with
1>          [
1>              _Myvec=std::_Vector_val<Sprite *,std::allocator<Sprite *>>,
1>              _Ty=Sprite *,
1>              _Valty=int
1>          ]
1>          ..\creatureui.cpp(438) : see reference to function template instantiation 'std::_Vector_iterator<_Myvec> std::vector<_Ty>::insert<int>(std::_Vector_const_iterator<_Myvec>,_Valty &&)' being compiled
1>          with
1>          [
1>              _Myvec=std::_Vector_val<Sprite *,std::allocator<Sprite *>>,
1>              _Ty=Sprite *,
1>              _Valty=int
1>          ]
1>  sprite.cpp
1>..\sprite.cpp(39): fatal error C1083: Cannot open include file: 'GL/glext.h': No such file or directory
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by ivucica** [comment]
This project is not under active development. There will be no support for it on part of its developers (incl. me). Even better, according to Github, I've last touched the Visual Studio project files 7 years ago. 

Answer to your problem is easily googlable and involves adding `GL/glext.h` into Visual Studio's include path.

**Comment by Pietia10** [comment]
Try active project
https://github.com/edubart/otclient


2016-03-20 11:44 GMT+01:00 Ivan Vučica <notifications@github.com>:
